### ISSUE TITLE
一個建議: 可以把uni交易序號 & 物流碼寫到meta裡嗎

### ISSUE THREAD

**Issue by gobido** [payuni/PAYUNi_for_WooCommerce#1]
例如以下方法: 
update_post_meta($order_id, "uni_TradeNo", $TradeNo);
update_post_meta($order_id, "uni_ShipTradeNo", $ShipTradeNo);

這樣可以在利用REST API時, 抓出該訂單的META. 目前是寫到NOTE, NOTE是ORDER的關聯, 而且還要去解析內容. 當然可以用系統訂單編號去查, 但是如果能在訂單成立時寫入是最好的了.

**Comment by payuni** [comment]
感謝您的建議，我們內部會再評估是否進行調整

**Comment by gobido** [comment]
我這麼用了給貴司參考.

309                 update_post_meta($encryptInfo['MerTradeNo'], 'uni_TradeNo', $encryptInfo['TradeNo']);
310                 //物流資訊
311                 if (isset($encryptInfo['ShipType'])) {
312                         update_post_meta($encryptInfo['MerTradeNo'], 'uni_ShipType', $encryptInfo['ShipType']);
313                         update_post_meta($encryptInfo['MerTradeNo'], 'uni_LgsType', $encryptInfo['LgsType']);
314                         update_post_meta($encryptInfo['MerTradeNo'], 'uni_ServiceType', $encryptInfo['ServiceType']);
315                         update_post_meta($encryptInfo['MerTradeNo'], 'uni_ShipTradeNo', $encryptInfo['ShipTradeNo']);
316                         if( $encryptInfo['ShipType'] == '1' ){
317                                 update_post_meta($encryptInfo['MerTradeNo'] , '_shipping_first_name',$encryptInfo['Consignee'] );
318                                 update_post_meta($encryptInfo['MerTradeNo'] , '_shipping_phone',$encryptInfo['ConsigneeMobile'] );
319                                 update_post_meta($encryptInfo['MerTradeNo'] , '_shipping_address_1',$encryptInfo['StoreID'] . $encryptInfo['StoreName']);
320                                 update_post_meta($encryptInfo['MerTradeNo'], '_shipping_address_2', $encryptInfo['StoreAddr']);
321                         }
322                 }
