### ISSUE TITLE
購物車結帳時支付方式無法顯示

### ISSUE THREAD

**Issue by jiyuuni** [payuni/PAYUNi_for_WooCommerce#4]
PAYUNi您好，如題，
使用docker image [6.4.3-php8.1-apache](https://github.com/docker-library/wordpress/blob/06f28e291877002359e1075e4260123de5403551/latest/php8.1/apache/Dockerfile)
部屬、安裝最新版WooCommerce，並按指示設定完商店參數後，在購物車結帳頁面並未跳出統一金流PAYUNi選項。

**Comment by payuni** [comment]
請問是否可提供模組設定畫面

**Comment by jiyuuni** [comment]
![image](https://github.com/payuni/PAYUNi_for_WooCommerce/assets/14539506/20661c9c-98bb-4ed3-b078-7462d87521d5)
![image](https://github.com/payuni/PAYUNi_for_WooCommerce/assets/14539506/d792aa79-4157-4d70-8708-33d347598080)

**Comment by jiyuuni** [comment]
![image](https://github.com/payuni/PAYUNi_for_WooCommerce/assets/14539506/098c4db0-12e7-4538-895e-82bda04b00a6)

**Comment by payuni** [comment]
請問是否可提供商店代號？

**Comment by jiyuuni** [comment]
U03401525

**Comment by payuni** [comment]
請確認支付工具是否為啟用的狀態 如下圖所示
![1709278787927_0](https://github.com/payuni/PAYUNi_for_WooCommerce/assets/111719316/6becb753-1c7c-4016-bdb2-c830aba8ad00)

另該商店代號為正式商店代號，非測試區商店代號
故需取消下圖紅框處的勾勾
![1709278834955_0](https://github.com/payuni/PAYUNi_for_WooCommerce/assets/111719316/7898daed-841c-4d14-aff1-0a193b21c365)

以上再煩請確認，感謝

**Comment by jiyuuni** [comment]
已按照上方指示設定，還是沒有出現該支付選項，
其他模組則會顯示。
![image](https://github.com/payuni/PAYUNi_for_WooCommerce/assets/14539506/8e1f30e3-9451-42f6-883c-f720feb8c841)

**Comment by payuni** [comment]
經測試使用使用docker image [6.4.3-php8.1-apache](https://github.com/docker-library/wordpress/blob/06f28e291877002359e1075e4260123de5403551/latest/php8.1/apache/Dockerfile)的確會發生以上問題
但我們在其他環境重新建制皆可正常執行
請貴司針對image的設定檢查是否有缺少相關設定，再麻煩自行排查，感謝。

**Comment by jiyuuni** [comment]
好的，瞭解了，謝謝您們。
